### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by bunnyblue** [liudongmiao/Xposed#4]
In file included from xposed/app_main.cpp:28:0:
xposed/xposed.h:9:29: fatal error: alloc/HeapTable.h: No such file or directory
compilation terminated.

build at android 4.3,build failure

**Comment by liudongmiao** [comment]
As this project is only for api-10, so please don't compile it on higher version.
`alloc/HeapTable.h` is exist on the api-10's dalvik, so please checkout the dalvik's android-2.3.X code.

**Comment by bunnyblue** [comment]
thaks  for your reply.
I checkout   https://android.googlesource.com/a/platform/manifest -b android-2.3.3_r1 and unzip xposed to sources,mm xposed, but build  failure.Before  I put Xposed to source ,build is ok.
build log is here

PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=2.3.3
TARGET_PRODUCT=generic
TARGET_BUILD_VARIANT=eng
TARGET_SIMULATOR=false
TARGET_BUILD_TYPE=release
TARGET_BUILD_APPS=
TARGET_ARCH=arm
HOST_ARCH=x86
HOST_OS=linux
HOST_BUILD_TYPE=release
BUILD_ID=GRI40


target thumb C++: xposed <= Xposed-master/app_main.cpp
In file included from dalvik/vm/Dalvik.h:46,
                 from Xposed-master/xposed.h:8,
                 from Xposed-master/app_main.cpp:28:
dalvik/vm/IndirectRefTable.h: In function 'IndirectRefKind dvmGetIndirectRefType(void*)':
dalvik/vm/IndirectRefTable.h:239: error: invalid conversion from 'u4' to 'IndirectRefKind'
In file included from dalvik/vm/Dalvik.h:72,
                 from Xposed-master/xposed.h:8,
                 from Xposed-master/app_main.cpp:28:
dalvik/vm/analysis/RegisterMap.h: In function 'RegisterMapFormat dvmRegisterMapGetFormat(const RegisterMap*)':
dalvik/vm/analysis/RegisterMap.h:70: error: invalid conversion from 'int' to 'RegisterMapFormat'
In file included from dalvik/vm/Dalvik.h:75,
                 from Xposed-master/xposed.h:8,
                 from Xposed-master/app_main.cpp:28:
dalvik/libdex/InstrUtils.h: At global scope:
dalvik/libdex/InstrUtils.h:39: error: using typedef-name 'InstructionFormat' after 'enum'
dalvik/libdex/InstrUtils.h:38: error: 'InstructionFormat' has a previous declaration here
dalvik/libdex/InstrUtils.h:97: error: using typedef-name 'InstructionFlags' after 'enum'
dalvik/libdex/InstrUtils.h:96: error: 'InstructionFlags' has a previous declaration here
In file included from dalvik/vm/Dalvik.h:87,
                 from Xposed-master/xposed.h:8,
                 from Xposed-master/app_main.cpp:28:
dalvik/vm/oo/ObjectInlines.h: In function 'Object* dvmGetFieldObject(const Object*, int)':
dalvik/vm/oo/ObjectInlines.h:79: error: invalid conversion from 'void*' to 'Object*'
dalvik/vm/oo/ObjectInlines.h: In function 's8 dvmGetFieldLongVolatile(const Object*, int)':
dalvik/vm/oo/ObjectInlines.h:108: error: invalid conversion from 'void*' to 'const s8*'
dalvik/vm/oo/ObjectInlines.h: In function 'double dvmGetFieldDoubleVolatile(const Object*, int)':
dalvik/vm/oo/ObjectInlines.h:115: error: invalid conversion from 'void*' to 'const s8*'
dalvik/vm/oo/ObjectInlines.h: In function 'void dvmSetFieldObject(Object*, int, Object*)':
dalvik/vm/oo/ObjectInlines.h:150: error: invalid conversion from 'void*' to 'JValue*'
dalvik/vm/oo/ObjectInlines.h: In function 'void dvmSetFieldLongVolatile(Object*, int, s8)':
dalvik/vm/oo/ObjectInlines.h:178: error: invalid conversion from 'void*' to 's8*'
dalvik/vm/oo/ObjectInlines.h: In function 'Object* dvmGetStaticFieldObject(const StaticField*)':
dalvik/vm/oo/ObjectInlines.h:227: error: invalid conversion from 'void*' to 'Object*
 

********************************************
If not'd include xposed,build is success. include  Xposed,build error.

**Comment by bunnyblue** [comment]
I need modify system source code？

**Comment by liudongmiao** [comment]
yes, you need to modify some code, here is the patch for dalvik: 
https://github.com/rovo89/Xposed/blob/2fd7d034ea2b15f9c10e0604ccc408dae444a10f/dalvik.c.patch

We need this patch, as there are differencence between the c++ (xposed) and c (dalvik). BTW, android rewrite the dalvik in c++ after android 2.3.

**Comment by bunnyblue** [comment]
Great Work.Thank You .
